# Generated by Django 2.2.7 on 2019-11-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_authorized',
        ),
        migrations.AddField(
            model_name='vendor',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
