# Generated by Django 2.2.7 on 2019-11-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blog_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_url',
        ),
    ]
