# Generated by Django 2.2.7 on 2019-11-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191124_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_authorized',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
